# Content types to search
search:
  - page
  - data
  - style
  - unknown # Speical flag for anything not in the extension list

# List of extensions to categorize urls by
extensions:
  # List of extensions considered pages and will be recursively searched
  page:
    - .html
    - .htm
    - .htc
    - .dhtml
    - .shtml
    - .phtml
    - .zhtml
    - .mht
    - .cshtml
    - .xhtm
    - .site
    - .php
    - .aspx
    - .ssp
    - .mjs
  # Scripts will be mapped, but not searched
  script:
    - .js
    - .cjs
    - .cs
    - .ts
    - .tsx
    - .es
    - .es6
    - .jsx
  # Data will be mapped and searched
  data:
    - .json
    - .xml
  # Styles will be mapped and searched
  style:
    - .css
    - .scss
    - .sass
  # Media files will be mapped but not searched
  media:
    - .png
    - .jpg
    - .jpeg
    - .svg
    - .mp3
    - .mp4
  # Document files will be mapped but not searched
  document:
    - .pdf
    - .doc
    - .docx
    - .xls
    - .xlsx
    - .ppt
    - .pptx
    - .odt
    - .ods
  # Files of special interest that will be highlighted, but not searched
  special:
    - .htaccess
    - .pub
    - .cert
    - .txt

# List of urls to ignore when matched
# These mostly contain well-known urls to schemas and other configurations
ignorelist:
  - http://www.w3.org/2000/svg
  - http://www.w3.org/1999/xlink